### ISSUE TITLE
`load_locales!()` does not work with leptos `0.4.10`

### ISSUE THREAD

**Issue by dessalines** [Baptistemontan/leptos_i18n#46]
Error:

```
error[E0061]: this function takes 2 arguments but 1 argument was supplied
src/lib.rs:1:1
leptos_i18n::load_locales!();
argument of type `leptos::Scope` is missing
note: method defined here
/home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.4.10/src/lib.rs:231:8231
fn collect_view(self, cx: Scope) -> View;
= note: this error originates in the macro `leptos_i18n::load_locales` (in Nightly builds, run with -Z macro-backtrace for more info)
help: provide the argument1   | 
leptos_i18n::load_locales!()(leptos_i18n::load_locales!(), /* leptos::Scope */);
```

**Comment by Baptistemontan** [comment]
What version are you using? Seams like you use `v0.2.0-beta` which is for Leptos `v0.5.0-beta`, if you use Leptos `v0.4.x` use Leptos i18n `v0.1.x`

**Comment by Baptistemontan** [comment]
If you switch to `v0.1` you will probably get the error with the configuration file not found, this is because it has been removed with `v0.2` and the README reflect `v0.2`, if you want the readme for `v0.1` you can look at the latest `v0.1` tag: https://github.com/Baptistemontan/leptos_i18n/tree/v0.1.3

**Comment by dessalines** [comment]
Ah okay thanks, wasn't too clear.
